export type UserRole =
  | 'ROLE_SYS_ADMIN'
  | 'ROLE_ORG_ADMIN'
  | 'ROLE_DOCTOR'
  | 'ROLE_NURSE'
  | 'ROLE_RECEPTIONIST'
  | 'ROLE_LAB_TECH'
  | 'ROLE_PHARMACIST'
  | 'ROLE_BILLING'
  | 'ROLE_PATIENT'
  | 'ROLE_AUDITOR'
  | 'ROLE_ADMIN';

export enum Capability {
  // Patient / MPI Operations
  PATIENT_READ = 'PATIENT_READ',
  PATIENT_CREATE = 'PATIENT_CREATE',
  PATIENT_UPDATE_DEMOGRAPHICS = 'PATIENT_UPDATE_DEMOGRAPHICS',
  PATIENT_UPDATE_CLINICAL = 'PATIENT_UPDATE_CLINICAL',

  // Clinical Operations
  ALLERGY_READ = 'ALLERGY_READ',
  ALLERGY_CREATE = 'ALLERGY_CREATE',
  ALLERGY_UPDATE_STATUS = 'ALLERGY_UPDATE_STATUS',

  DIAGNOSIS_READ = 'DIAGNOSIS_READ',
  DIAGNOSIS_CREATE = 'DIAGNOSIS_CREATE',

  PRESCRIPTION_READ = 'PRESCRIPTION_READ',
  PRESCRIPTION_CREATE = 'PRESCRIPTION_CREATE',
  PRESCRIPTION_UPDATE_STATUS = 'PRESCRIPTION_UPDATE_STATUS',
  MEDICATION_DISPENSE = 'MEDICATION_DISPENSE',

  VITALS_READ = 'VITALS_READ',
  VITALS_CREATE = 'VITALS_CREATE',

  ENCOUNTER_READ = 'ENCOUNTER_READ',
  ENCOUNTER_CREATE = 'ENCOUNTER_CREATE',

  MEDICAL_RECORD_READ = 'MEDICAL_RECORD_READ',
  MEDICAL_RECORD_CREATE = 'MEDICAL_RECORD_CREATE',

  // Lab & Diagnostic Operations
  LAB_ORDER_CREATE = 'LAB_ORDER_CREATE',
  LAB_RESULT_CREATE = 'LAB_RESULT_CREATE',
  LAB_RESULT_READ = 'LAB_RESULT_READ',

  // Appointment & Workflow Operations
  APPOINTMENT_READ = 'APPOINTMENT_READ',
  APPOINTMENT_SCHEDULE = 'APPOINTMENT_SCHEDULE',
  APPOINTMENT_STATUS_UPDATE = 'APPOINTMENT_STATUS_UPDATE',
  APPOINTMENT_CHECKIN = 'APPOINTMENT_CHECKIN',
  APPOINTMENT_TRIAGE = 'APPOINTMENT_TRIAGE',
  APPOINTMENT_DOCTOR_CONSULT = 'APPOINTMENT_DOCTOR_CONSULT',
  APPOINTMENT_BILLING_GENERATE = 'APPOINTMENT_BILLING_GENERATE',
  APPOINTMENT_NOTES_ADD = 'APPOINTMENT_NOTES_ADD',
  APPOINTMENT_CANCEL = 'APPOINTMENT_CANCEL',

  // Billing Operations
  INVOICE_CREATE = 'INVOICE_CREATE',
  INVOICE_READ = 'INVOICE_READ',

  // Administrative & Audit Operations
  ADMIN_USER_MANAGE = 'ADMIN_USER_MANAGE',
  ADMIN_FHIR_INGEST = 'ADMIN_FHIR_INGEST',
  AUDIT_LOG_READ = 'AUDIT_LOG_READ',
  FHIR_QUERY = 'FHIR_QUERY',
}

/**
 * Mapping of User Roles to Authorized Capabilities across all 10 roles.
 */
export const ROLE_CAPABILITY_MAP: Record<UserRole, Capability[]> = {
  ROLE_SYS_ADMIN: Object.values(Capability),
  ROLE_ORG_ADMIN: Object.values(Capability),
  ROLE_ADMIN: Object.values(Capability),

  ROLE_DOCTOR: [
    Capability.PATIENT_READ,
    Capability.PATIENT_UPDATE_DEMOGRAPHICS,
    Capability.PATIENT_UPDATE_CLINICAL,
    Capability.ALLERGY_READ,
    Capability.ALLERGY_CREATE,
    Capability.ALLERGY_UPDATE_STATUS,
    Capability.DIAGNOSIS_READ,
    Capability.DIAGNOSIS_CREATE,
    Capability.PRESCRIPTION_READ,
    Capability.PRESCRIPTION_CREATE,
    Capability.PRESCRIPTION_UPDATE_STATUS,
    Capability.VITALS_READ,
    Capability.VITALS_CREATE,
    Capability.ENCOUNTER_READ,
    Capability.ENCOUNTER_CREATE,
    Capability.MEDICAL_RECORD_READ,
    Capability.MEDICAL_RECORD_CREATE,
    Capability.LAB_ORDER_CREATE,
    Capability.LAB_RESULT_READ,
    Capability.APPOINTMENT_READ,
    Capability.APPOINTMENT_SCHEDULE,
    Capability.APPOINTMENT_STATUS_UPDATE,
    Capability.APPOINTMENT_DOCTOR_CONSULT,
    Capability.APPOINTMENT_NOTES_ADD,
    Capability.APPOINTMENT_CANCEL,
    Capability.FHIR_QUERY,
  ],

  ROLE_NURSE: [
    Capability.PATIENT_READ,
    Capability.PATIENT_UPDATE_DEMOGRAPHICS,
    Capability.PATIENT_UPDATE_CLINICAL,
    Capability.ALLERGY_READ,
    Capability.ALLERGY_CREATE,
    Capability.ALLERGY_UPDATE_STATUS,
    Capability.DIAGNOSIS_READ,
    Capability.PRESCRIPTION_READ,
    Capability.PRESCRIPTION_UPDATE_STATUS,
    Capability.VITALS_READ,
    Capability.VITALS_CREATE,
    Capability.ENCOUNTER_READ,
    Capability.ENCOUNTER_CREATE,
    Capability.MEDICAL_RECORD_READ,
    Capability.MEDICAL_RECORD_CREATE,
    Capability.LAB_RESULT_READ,
    Capability.APPOINTMENT_READ,
    Capability.APPOINTMENT_TRIAGE,
    Capability.APPOINTMENT_NOTES_ADD,
    Capability.APPOINTMENT_CANCEL,
    Capability.FHIR_QUERY,
  ],

  ROLE_RECEPTIONIST: [
    Capability.PATIENT_READ,
    Capability.PATIENT_CREATE,
    Capability.PATIENT_UPDATE_DEMOGRAPHICS,
    Capability.APPOINTMENT_READ,
    Capability.APPOINTMENT_SCHEDULE,
    Capability.APPOINTMENT_STATUS_UPDATE,
    Capability.APPOINTMENT_CHECKIN,
    Capability.APPOINTMENT_BILLING_GENERATE,
    Capability.APPOINTMENT_NOTES_ADD,
    Capability.APPOINTMENT_CANCEL,
    Capability.INVOICE_READ,
    Capability.FHIR_QUERY,
  ],

  ROLE_LAB_TECH: [
    Capability.PATIENT_READ,
    Capability.LAB_ORDER_CREATE,
    Capability.LAB_RESULT_CREATE,
    Capability.LAB_RESULT_READ,
    Capability.APPOINTMENT_READ,
    Capability.FHIR_QUERY,
  ],

  ROLE_PHARMACIST: [
    Capability.PATIENT_READ,
    Capability.PRESCRIPTION_READ,
    Capability.PRESCRIPTION_UPDATE_STATUS,
    Capability.MEDICATION_DISPENSE,
    Capability.ALLERGY_READ,
    Capability.DIAGNOSIS_READ,
    Capability.FHIR_QUERY,
  ],

  ROLE_BILLING: [
    Capability.PATIENT_READ,
    Capability.INVOICE_CREATE,
    Capability.INVOICE_READ,
    Capability.APPOINTMENT_READ,
    Capability.APPOINTMENT_BILLING_GENERATE,
    Capability.FHIR_QUERY,
  ],

  ROLE_PATIENT: [
    Capability.PATIENT_READ,
    Capability.PATIENT_UPDATE_DEMOGRAPHICS,
    Capability.ALLERGY_READ,
    Capability.DIAGNOSIS_READ,
    Capability.PRESCRIPTION_READ,
    Capability.VITALS_READ,
    Capability.ENCOUNTER_READ,
    Capability.MEDICAL_RECORD_READ,
    Capability.LAB_RESULT_READ,
    Capability.INVOICE_READ,
    Capability.APPOINTMENT_READ,
    Capability.APPOINTMENT_SCHEDULE,
    Capability.APPOINTMENT_NOTES_ADD,
    Capability.APPOINTMENT_CANCEL,
    Capability.FHIR_QUERY,
  ],

  ROLE_AUDITOR: [
    Capability.PATIENT_READ,
    Capability.ALLERGY_READ,
    Capability.DIAGNOSIS_READ,
    Capability.PRESCRIPTION_READ,
    Capability.VITALS_READ,
    Capability.ENCOUNTER_READ,
    Capability.MEDICAL_RECORD_READ,
    Capability.LAB_RESULT_READ,
    Capability.INVOICE_READ,
    Capability.APPOINTMENT_READ,
    Capability.AUDIT_LOG_READ,
    Capability.FHIR_QUERY,
  ],
};
