-- ==============================================================================
-- Sentinel EHR Synthetic Patient Data Seed Script
-- Generated on: 2026-08-14 23:35:33
-- Total Patients Generated: 5
-- ==============================================================================

-- 1. Patients Table Seeding
INSERT INTO patients (patient_code, abha_id, national_id, full_name, date_of_birth, gender, blood_type, phone, email, address, pin_code, emergency_contact, insurance_provider, insurance_policy_number, insurance_group_number, coverage_plan, medical_alerts) VALUES ('MRN-965987', '91-8051-6387-5709', 'AADHAAR-8458-4689', 'Kabir Rao', '1983-03-15', 'Male', 'AB+', '+91 9147444615', 'kabir.rao50@sentinel-health.in', 'House No. 123, Block C, Mumbai', '400001', 'Kin (Sibling) - +91 7555605154', 'Bajaj Allianz', 'POL-500412', 'GRP-1299', 'Health Guard Platinum Plan', 'High Fidelity Synthetic Record | Blood Type: AB+ | Dept: Neurology');
INSERT INTO patients (patient_code, abha_id, national_id, full_name, date_of_birth, gender, blood_type, phone, email, address, pin_code, emergency_contact, insurance_provider, insurance_policy_number, insurance_group_number, coverage_plan, medical_alerts) VALUES ('MRN-951497', '91-4449-1252-8746', 'AADHAAR-6548-2562', 'Rohan Gupta', '1952-09-09', 'Male', 'O-', '+91 9734887468', 'rohan.gupta97@sentinel-health.in', 'House No. 110, Block D, Bengaluru', '560001', 'Kin (Spouse) - +91 8202863211', 'Care Health Insurance', 'POL-520431', 'GRP-5432', 'Care Supreme Gold Protection', 'High Fidelity Synthetic Record | Blood Type: O- | Dept: Cardiovascular Medicine');
INSERT INTO patients (patient_code, abha_id, national_id, full_name, date_of_birth, gender, blood_type, phone, email, address, pin_code, emergency_contact, insurance_provider, insurance_policy_number, insurance_group_number, coverage_plan, medical_alerts) VALUES ('MRN-306694', '91-5521-1782-9119', 'AADHAAR-4089-9332', 'Sneha Rao', '1999-07-16', 'Female', 'A-', '+91 8799542134', 'sneha.rao72@sentinel-health.in', 'House No. 137, Block B, Delhi', '110001', 'Kin (Sibling) - +91 9880548003', 'HDFC ERGO Health', 'POL-234096', 'GRP-3594', 'Optima Secure Comprehensive', 'High Fidelity Synthetic Record | Blood Type: A- | Dept: Endocrinology');
INSERT INTO patients (patient_code, abha_id, national_id, full_name, date_of_birth, gender, blood_type, phone, email, address, pin_code, emergency_contact, insurance_provider, insurance_policy_number, insurance_group_number, coverage_plan, medical_alerts) VALUES ('MRN-358884', '91-1853-6280-2393', 'AADHAAR-4808-8706', 'Nisha Gupta', '2000-03-16', 'Female', 'A+', '+91 9639839519', 'nisha.gupta51@sentinel-health.in', 'House No. 70, Block B, Kolkata', '700001', 'Kin (Sibling) - +91 7709922953', 'Star Health Insurance', 'POL-915168', 'GRP-5979', 'Comprehensive PM-JAY & Health Shield', 'High Fidelity Synthetic Record | Blood Type: A+ | Dept: Gastroenterology');
INSERT INTO patients (patient_code, abha_id, national_id, full_name, date_of_birth, gender, blood_type, phone, email, address, pin_code, emergency_contact, insurance_provider, insurance_policy_number, insurance_group_number, coverage_plan, medical_alerts) VALUES ('MRN-880531', '91-3996-7109-9320', 'AADHAAR-6561-4073', 'Siddharth Deshmukh', '1987-03-15', 'Male', 'AB+', '+91 8472442351', 'siddharth.deshmukh60@sentinel-health.in', 'House No. 12, Block D, Ahmedabad', '380001', 'Kin (Spouse) - +91 8821485675', 'HDFC ERGO Health', 'POL-899623', 'GRP-3554', 'Optima Secure Comprehensive', 'High Fidelity Synthetic Record | Blood Type: AB+ | Dept: General Internal Medicine');

-- 2. Encounters Table Seeding
INSERT INTO encounters (patient_id, attending_provider_id, encounter_type, chief_complaint, clinical_notes, discharge_summary, status) VALUES (1, 2, 'EMERGENCY', 'Acute retrosternal chest discomfort radiating to left arm during physical exertion.', 'Patient Kabir Rao presented with acute retrosternal chest discomfort radiating to left arm during physical exertion. Physical examination intact. Plan formulated.', 'Patient stable at time of discharge. Advice given for compliance with medication.', 'COMPLETED');
INSERT INTO encounters (patient_id, attending_provider_id, encounter_type, chief_complaint, clinical_notes, discharge_summary, status) VALUES (1, 2, 'EMERGENCY', 'Bilateral knee joint stiffness and localized swelling worse in the morning.', 'Patient Kabir Rao presented with bilateral knee joint stiffness and localized swelling worse in the morning. Physical examination intact. Plan formulated.', 'Patient stable at time of discharge. Advice given for compliance with medication.', 'COMPLETED');
INSERT INTO encounters (patient_id, attending_provider_id, encounter_type, chief_complaint, clinical_notes, discharge_summary, status) VALUES (2, 2, 'OUTPATIENT', 'Acute severe right lower quadrant abdominal pain accompanied by nausea.', 'Patient Rohan Gupta presented with acute severe right lower quadrant abdominal pain accompanied by nausea. Physical examination intact. Plan formulated.', 'Patient stable at time of discharge. Advice given for compliance with medication.', 'COMPLETED');
INSERT INTO encounters (patient_id, attending_provider_id, encounter_type, chief_complaint, clinical_notes, discharge_summary, status) VALUES (2, 2, 'EMERGENCY', 'Acute severe right lower quadrant abdominal pain accompanied by nausea.', 'Patient Rohan Gupta presented with acute severe right lower quadrant abdominal pain accompanied by nausea. Physical examination intact. Plan formulated.', 'Patient stable at time of discharge. Advice given for compliance with medication.', 'COMPLETED');
INSERT INTO encounters (patient_id, attending_provider_id, encounter_type, chief_complaint, clinical_notes, discharge_summary, status) VALUES (3, 2, 'INPATIENT', 'Persistent dry cough, mild dyspnea, and low-grade evening pyrexia for 5 days.', 'Patient Sneha Rao presented with persistent dry cough, mild dyspnea, and low-grade evening pyrexia for 5 days. Physical examination intact. Plan formulated.', 'Patient stable at time of discharge. Advice given for compliance with medication.', 'COMPLETED');
INSERT INTO encounters (patient_id, attending_provider_id, encounter_type, chief_complaint, clinical_notes, discharge_summary, status) VALUES (3, 2, 'OUTPATIENT', 'Acute retrosternal chest discomfort radiating to left arm during physical exertion.', 'Patient Sneha Rao presented with acute retrosternal chest discomfort radiating to left arm during physical exertion. Physical examination intact. Plan formulated.', 'Patient stable at time of discharge. Advice given for compliance with medication.', 'COMPLETED');
INSERT INTO encounters (patient_id, attending_provider_id, encounter_type, chief_complaint, clinical_notes, discharge_summary, status) VALUES (4, 2, 'TELEHEALTH', 'Acute retrosternal chest discomfort radiating to left arm during physical exertion.', 'Patient Nisha Gupta presented with acute retrosternal chest discomfort radiating to left arm during physical exertion. Physical examination intact. Plan formulated.', 'Patient stable at time of discharge. Advice given for compliance with medication.', 'COMPLETED');
INSERT INTO encounters (patient_id, attending_provider_id, encounter_type, chief_complaint, clinical_notes, discharge_summary, status) VALUES (4, 2, 'OUTPATIENT', 'Acute severe right lower quadrant abdominal pain accompanied by nausea.', 'Patient Nisha Gupta presented with acute severe right lower quadrant abdominal pain accompanied by nausea. Physical examination intact. Plan formulated.', 'Patient stable at time of discharge. Advice given for compliance with medication.', 'COMPLETED');
INSERT INTO encounters (patient_id, attending_provider_id, encounter_type, chief_complaint, clinical_notes, discharge_summary, status) VALUES (5, 2, 'TELEHEALTH', 'Routine follow-up for Glycemic and Blood Pressure control evaluation.', 'Patient Siddharth Deshmukh presented with routine follow-up for glycemic and blood pressure control evaluation. Physical examination intact. Plan formulated.', 'Patient stable at time of discharge. Advice given for compliance with medication.', 'COMPLETED');
INSERT INTO encounters (patient_id, attending_provider_id, encounter_type, chief_complaint, clinical_notes, discharge_summary, status) VALUES (5, 2, 'EMERGENCY', 'Acute retrosternal chest discomfort radiating to left arm during physical exertion.', 'Patient Siddharth Deshmukh presented with acute retrosternal chest discomfort radiating to left arm during physical exertion. Physical examination intact. Plan formulated.', 'Patient stable at time of discharge. Advice given for compliance with medication.', 'COMPLETED');

-- 3. Diagnoses Table Seeding
INSERT INTO diagnoses (patient_id, doctor_id, condition_name, icd_code, snomed_code, onset_date, status, notes) VALUES (1, 2, 'Chronic Kidney Disease Stage 3', 'N18.3', '43314009', '2013-03-15', 'ACTIVE', 'Moderate GFR reduction (45-59 mL/min/1.73m2). Nephrology monitoring active.');
INSERT INTO diagnoses (patient_id, doctor_id, condition_name, icd_code, snomed_code, onset_date, status, notes) VALUES (2, 2, 'Chronic Kidney Disease Stage 3', 'N18.3', '43314009', '1982-09-09', 'ACTIVE', 'Moderate GFR reduction (45-59 mL/min/1.73m2). Nephrology monitoring active.');
INSERT INTO diagnoses (patient_id, doctor_id, condition_name, icd_code, snomed_code, onset_date, status, notes) VALUES (3, 2, 'Essential Hypertension', 'I10', '59621000', '2029-07-16', 'ACTIVE', 'Longitudinal blood pressure monitoring required. Prescribed ARB/ACEi therapy.');
INSERT INTO diagnoses (patient_id, doctor_id, condition_name, icd_code, snomed_code, onset_date, status, notes) VALUES (4, 2, 'Hyperlipidemia', 'E78.5', '55822004', '2030-03-16', 'ACTIVE', 'Elevated LDL cholesterol profile. Statin therapy prescribed with low-fat diet plan.');
INSERT INTO diagnoses (patient_id, doctor_id, condition_name, icd_code, snomed_code, onset_date, status, notes) VALUES (5, 2, 'Chronic Kidney Disease Stage 3', 'N18.3', '43314009', '2017-03-15', 'ACTIVE', 'Moderate GFR reduction (45-59 mL/min/1.73m2). Nephrology monitoring active.');

-- 4. Vitals Table Seeding
INSERT INTO vitals (patient_id, recorded_by_id, blood_pressure, heart_rate, temperature, oxygen_saturation, respiratory_rate, weight_kg, height_cm, bmi, blood_glucose) VALUES (1, 3, '145/83', 62, 37.0, 99, 18, 85.7, 166.5, 30.9, 126);
INSERT INTO vitals (patient_id, recorded_by_id, blood_pressure, heart_rate, temperature, oxygen_saturation, respiratory_rate, weight_kg, height_cm, bmi, blood_glucose) VALUES (2, 3, '117/84', 78, 36.5, 97, 14, 79.0, 170.1, 27.3, 98);
INSERT INTO vitals (patient_id, recorded_by_id, blood_pressure, heart_rate, temperature, oxygen_saturation, respiratory_rate, weight_kg, height_cm, bmi, blood_glucose) VALUES (3, 3, '121/91', 68, 37.3, 96, 14, 67.2, 176.1, 21.7, 95);
INSERT INTO vitals (patient_id, recorded_by_id, blood_pressure, heart_rate, temperature, oxygen_saturation, respiratory_rate, weight_kg, height_cm, bmi, blood_glucose) VALUES (4, 3, '110/81', 72, 36.6, 96, 14, 67.9, 174.8, 22.2, 109);
INSERT INTO vitals (patient_id, recorded_by_id, blood_pressure, heart_rate, temperature, oxygen_saturation, respiratory_rate, weight_kg, height_cm, bmi, blood_glucose) VALUES (5, 3, '136/86', 81, 36.9, 100, 20, 69.6, 184.3, 20.5, 100);

-- 5. Allergies Table Seeding
INSERT INTO allergies (patient_id, allergen_name, allergen_code, category, severity, reaction_description, status, recorded_by_id) VALUES (2, 'Ibuprofen', 'RxNorm-5640', 'DRUG', 'LIFE_THREATENING', 'Anaphylactic reaction with acute hypotension and airway compromise.', 'ACTIVE', 2);
INSERT INTO allergies (patient_id, allergen_name, allergen_code, category, severity, reaction_description, status, recorded_by_id) VALUES (3, 'Ibuprofen', 'RxNorm-5640', 'DRUG', 'LIFE_THREATENING', 'Anaphylactic reaction with acute hypotension and airway compromise.', 'ACTIVE', 2);
INSERT INTO allergies (patient_id, allergen_name, allergen_code, category, severity, reaction_description, status, recorded_by_id) VALUES (5, 'Peanuts', 'RxNorm-100234', 'FOOD', 'SEVERE', 'Oropharyngeal swelling, throat tightness, and systemic histamine release.', 'ACTIVE', 2);

-- 6. Prescriptions Table Seeding
INSERT INTO prescriptions (patient_id, doctor_id, medication_name, rx_norm_code, dosage, route, frequency, duration_days, refills, instructions, status) VALUES (1, 2, 'Pantoprazole Sodium', 'RxNorm-40790', '40mg', 'Oral', 'Once Daily', 30, 2, 'Take 30 minutes before morning breakfast.', 'ACTIVE');
INSERT INTO prescriptions (patient_id, doctor_id, medication_name, rx_norm_code, dosage, route, frequency, duration_days, refills, instructions, status) VALUES (2, 2, 'Lisinopril', 'RxNorm-29046', '10mg', 'Oral', 'Once Daily', 30, 2, 'Take in the morning. Monitor serum potassium and blood pressure.', 'ACTIVE');
INSERT INTO prescriptions (patient_id, doctor_id, medication_name, rx_norm_code, dosage, route, frequency, duration_days, refills, instructions, status) VALUES (3, 2, 'Lisinopril', 'RxNorm-29046', '10mg', 'Oral', 'Once Daily', 30, 2, 'Take in the morning. Monitor serum potassium and blood pressure.', 'ACTIVE');
INSERT INTO prescriptions (patient_id, doctor_id, medication_name, rx_norm_code, dosage, route, frequency, duration_days, refills, instructions, status) VALUES (4, 2, 'Atorvastatin Calcium', 'RxNorm-83367', '20mg', 'Oral', 'Once Daily', 30, 2, 'Take at bedtime with or without food.', 'ACTIVE');
INSERT INTO prescriptions (patient_id, doctor_id, medication_name, rx_norm_code, dosage, route, frequency, duration_days, refills, instructions, status) VALUES (5, 2, 'Lisinopril', 'RxNorm-29046', '10mg', 'Oral', 'Once Daily', 30, 2, 'Take in the morning. Monitor serum potassium and blood pressure.', 'ACTIVE');

-- 7. Lab Orders & Lab Results Seeding
INSERT INTO lab_orders (patient_id, encounter_id, ordering_provider_id, test_name, loinc_code, category, status, specimen_barcode, clinical_notes) VALUES (1, 1, 2, 'Comprehensive Metabolic & Lipid Panel', '24331-1', 'LABORATORY', 'COMPLETED', 'SP-372437', 'Routine baseline clinical panel evaluation.');
INSERT INTO lab_orders (patient_id, encounter_id, ordering_provider_id, test_name, loinc_code, category, status, specimen_barcode, clinical_notes) VALUES (2, 3, 2, 'Comprehensive Metabolic & Lipid Panel', '24331-1', 'LABORATORY', 'COMPLETED', 'SP-267532', 'Routine baseline clinical panel evaluation.');
INSERT INTO lab_orders (patient_id, encounter_id, ordering_provider_id, test_name, loinc_code, category, status, specimen_barcode, clinical_notes) VALUES (3, 5, 2, 'Comprehensive Metabolic & Lipid Panel', '24331-1', 'LABORATORY', 'COMPLETED', 'SP-874636', 'Routine baseline clinical panel evaluation.');
INSERT INTO lab_orders (patient_id, encounter_id, ordering_provider_id, test_name, loinc_code, category, status, specimen_barcode, clinical_notes) VALUES (4, 7, 2, 'Comprehensive Metabolic & Lipid Panel', '24331-1', 'LABORATORY', 'COMPLETED', 'SP-148874', 'Routine baseline clinical panel evaluation.');
INSERT INTO lab_orders (patient_id, encounter_id, ordering_provider_id, test_name, loinc_code, category, status, specimen_barcode, clinical_notes) VALUES (5, 9, 2, 'Comprehensive Metabolic & Lipid Panel', '24331-1', 'LABORATORY', 'COMPLETED', 'SP-816446', 'Routine baseline clinical panel evaluation.');
INSERT INTO lab_results (lab_order_id, parameter_name, loinc_code, result_value, unit, reference_range, is_critical, flag) VALUES (1, 'Fasting Blood Glucose', '1558-6', '126', 'mg/dL', '70-99 mg/dL', FALSE, 'ELEVATED');
INSERT INTO lab_results (lab_order_id, parameter_name, loinc_code, result_value, unit, reference_range, is_critical, flag) VALUES (2, 'Fasting Blood Glucose', '1558-6', '98', 'mg/dL', '70-99 mg/dL', FALSE, 'NORMAL');
INSERT INTO lab_results (lab_order_id, parameter_name, loinc_code, result_value, unit, reference_range, is_critical, flag) VALUES (3, 'Fasting Blood Glucose', '1558-6', '95', 'mg/dL', '70-99 mg/dL', FALSE, 'NORMAL');
INSERT INTO lab_results (lab_order_id, parameter_name, loinc_code, result_value, unit, reference_range, is_critical, flag) VALUES (4, 'Fasting Blood Glucose', '1558-6', '109', 'mg/dL', '70-99 mg/dL', FALSE, 'ELEVATED');
INSERT INTO lab_results (lab_order_id, parameter_name, loinc_code, result_value, unit, reference_range, is_critical, flag) VALUES (5, 'Fasting Blood Glucose', '1558-6', '100', 'mg/dL', '70-99 mg/dL', FALSE, 'ELEVATED');

-- 8. Medical Records Seeding
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, icd_code, symptoms, treatment_plan, notes) VALUES (1, 2, 'Chronic Kidney Disease Stage 3', 'N18.3', 'Bilateral knee joint stiffness and localized swelling worse in the morning.', 'Initiated Pantoprazole Sodium (40mg). Recommended low sodium diet and 30 minutes daily light aerobic exercise.', 'Longitudinal care plan logged for Kabir Rao.');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, icd_code, symptoms, treatment_plan, notes) VALUES (2, 2, 'Chronic Kidney Disease Stage 3', 'N18.3', 'Acute severe right lower quadrant abdominal pain accompanied by nausea.', 'Initiated Lisinopril (10mg). Recommended low sodium diet and 30 minutes daily light aerobic exercise.', 'Longitudinal care plan logged for Rohan Gupta.');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, icd_code, symptoms, treatment_plan, notes) VALUES (3, 2, 'Essential Hypertension', 'I10', 'Acute retrosternal chest discomfort radiating to left arm during physical exertion.', 'Initiated Lisinopril (10mg). Recommended low sodium diet and 30 minutes daily light aerobic exercise.', 'Longitudinal care plan logged for Sneha Rao.');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, icd_code, symptoms, treatment_plan, notes) VALUES (4, 2, 'Hyperlipidemia', 'E78.5', 'Acute severe right lower quadrant abdominal pain accompanied by nausea.', 'Initiated Atorvastatin Calcium (20mg). Recommended low sodium diet and 30 minutes daily light aerobic exercise.', 'Longitudinal care plan logged for Nisha Gupta.');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, icd_code, symptoms, treatment_plan, notes) VALUES (5, 2, 'Chronic Kidney Disease Stage 3', 'N18.3', 'Acute retrosternal chest discomfort radiating to left arm during physical exertion.', 'Initiated Lisinopril (10mg). Recommended low sodium diet and 30 minutes daily light aerobic exercise.', 'Longitudinal care plan logged for Siddharth Deshmukh.');