-- ==============================================================================
-- Sentinel EHR Database Schema Script (DDL)
-- Compatible with Database SQL Editors (H2 PostgreSQL Mode, PostgreSQL, MySQL)
-- ==============================================================================

CREATE TABLE IF NOT EXISTS departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(60) UNIQUE NOT NULL,
    code VARCHAR(20) UNIQUE NOT NULL,
    description VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_code VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    license_number VARCHAR(100) NOT NULL,
    email VARCHAR(150),
    phone VARCHAR(50),
    address VARCHAR(500),
    status VARCHAR(30) NOT NULL DEFAULT 'VERIFIED',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30) UNIQUE NOT NULL,
    description VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(60) UNIQUE NOT NULL,
    category VARCHAR(30) NOT NULL,
    description VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS role_permissions (
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
    FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    specialization VARCHAR(255),
    department VARCHAR(255),
    department_id BIGINT,
    organization_id BIGINT,
    license_number VARCHAR(255),
    qualifications VARCHAR(255),
    years_of_experience INT,
    medical_board_state VARCHAR(255),
    verification_status VARCHAR(255) DEFAULT 'VERIFIED',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE SET NULL,
    FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_code VARCHAR(255) UNIQUE NOT NULL,
    abha_id VARCHAR(255),
    national_id VARCHAR(255),
    full_name VARCHAR(255) NOT NULL,
    date_of_birth DATE,
    gender VARCHAR(255),
    blood_type VARCHAR(255),
    phone VARCHAR(255),
    email VARCHAR(255),
    address VARCHAR(255),
    pin_code VARCHAR(255),
    emergency_contact VARCHAR(255),
    insurance_provider VARCHAR(255),
    insurance_policy_number VARCHAR(255),
    insurance_group_number VARCHAR(255),
    coverage_plan VARCHAR(255),
    department VARCHAR(255),
    organization_id BIGINT,
    medical_alerts VARCHAR(1000),
    dietary_habits VARCHAR(255),
    smoking_status VARCHAR(255),
    alcohol_consumption VARCHAR(255),
    exercise_routine VARCHAR(255),
    food_allergies VARCHAR(255),
    past_medical_history VARCHAR(2000),
    serious_conditions VARCHAR(2000),
    surgeries_and_procedures VARCHAR(2000),
    family_medical_history VARCHAR(2000),
    user_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS beds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bed_code VARCHAR(255) UNIQUE NOT NULL,
    facility_name VARCHAR(255) DEFAULT 'Sentinel General Hospital',
    department_name VARCHAR(255) NOT NULL,
    ward_name VARCHAR(255) NOT NULL,
    room_number VARCHAR(255) NOT NULL,
    bed_number VARCHAR(255) NOT NULL,
    status VARCHAR(255) DEFAULT 'AVAILABLE',
    features VARCHAR(255),
    current_encounter_id BIGINT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS encounters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    attending_provider_id BIGINT NOT NULL,
    encounter_type VARCHAR(255) NOT NULL,
    chief_complaint VARCHAR(1000),
    clinical_notes VARCHAR(3000),
    discharge_summary VARCHAR(3000),
    status VARCHAR(255) DEFAULT 'ADMITTED',
    admission_type VARCHAR(255),
    admission_source VARCHAR(255),
    department_name VARCHAR(255),
    admission_diagnosis_icd VARCHAR(255),
    acuity_score INT,
    assigned_bed_id BIGINT,
    encounter_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    admission_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    discharge_time TIMESTAMP,
    FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    FOREIGN KEY (attending_provider_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (assigned_bed_id) REFERENCES beds(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS location_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    encounter_id BIGINT NOT NULL,
    bed_id BIGINT NOT NULL,
    department_name VARCHAR(255) NOT NULL,
    ward_name VARCHAR(255) NOT NULL,
    room_number VARCHAR(255) NOT NULL,
    bed_number VARCHAR(255) NOT NULL,
    start_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    end_time TIMESTAMP,
    transfer_reason VARCHAR(1000),
    transferred_by_id BIGINT,
    FOREIGN KEY (encounter_id) REFERENCES encounters(id) ON DELETE CASCADE,
    FOREIGN KEY (bed_id) REFERENCES beds(id) ON DELETE CASCADE,
    FOREIGN KEY (transferred_by_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS patient_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    encounter_id BIGINT,
    staff_user_id BIGINT NOT NULL,
    assignment_type VARCHAR(40) NOT NULL,
    department_name VARCHAR(255),
    status VARCHAR(20) DEFAULT 'ACTIVE',
    start_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    end_date TIMESTAMP,
    FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    FOREIGN KEY (encounter_id) REFERENCES encounters(id) ON DELETE CASCADE,
    FOREIGN KEY (staff_user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS break_glass_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    category VARCHAR(50) NOT NULL,
    justification VARCHAR(2000) NOT NULL,
    requested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    status VARCHAR(20) DEFAULT 'ACTIVE',
    client_ip VARCHAR(255),
    FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS lab_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    encounter_id BIGINT,
    ordering_provider_id BIGINT NOT NULL,
    test_name VARCHAR(255) NOT NULL,
    loinc_code VARCHAR(255),
    category VARCHAR(255) DEFAULT 'LABORATORY',
    status VARCHAR(255) DEFAULT 'ORDERED',
    specimen_barcode VARCHAR(255),
    ordered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    specimen_collected_at TIMESTAMP,
    in_process_at TIMESTAMP,
    resulted_at TIMESTAMP,
    reviewed_at TIMESTAMP,
    reviewed_by_id BIGINT,
    clinical_notes VARCHAR(1000),
    FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    FOREIGN KEY (encounter_id) REFERENCES encounters(id) ON DELETE CASCADE,
    FOREIGN KEY (ordering_provider_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (reviewed_by_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS lab_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lab_order_id BIGINT NOT NULL,
    parameter_name VARCHAR(255) NOT NULL,
    loinc_code VARCHAR(255),
    result_value VARCHAR(255) NOT NULL,
    unit VARCHAR(255),
    reference_range VARCHAR(255),
    is_critical BOOLEAN DEFAULT FALSE,
    flag VARCHAR(255),
    recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (lab_order_id) REFERENCES lab_orders(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS imaging_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    encounter_id BIGINT,
    ordering_provider_id BIGINT NOT NULL,
    modality VARCHAR(255) NOT NULL,
    procedure_name VARCHAR(255) NOT NULL,
    cpt_code VARCHAR(255),
    status VARCHAR(255) DEFAULT 'ORDERED',
    dicom_study_instance_uid VARCHAR(255),
    radiologist_report VARCHAR(4000),
    radiologist_id BIGINT,
    ordered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    scheduled_at TIMESTAMP,
    performed_at TIMESTAMP,
    report_generated_at TIMESTAMP,
    reviewed_at TIMESTAMP,
    FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    FOREIGN KEY (encounter_id) REFERENCES encounters(id) ON DELETE CASCADE,
    FOREIGN KEY (ordering_provider_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (radiologist_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS procedure_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    encounter_id BIGINT,
    ordering_provider_id BIGINT NOT NULL,
    procedure_name VARCHAR(255) NOT NULL,
    snomed_code VARCHAR(255),
    cpt_code VARCHAR(255),
    status VARCHAR(255) DEFAULT 'ORDERED',
    operative_report VARCHAR(4000),
    proceduralist_id BIGINT,
    ordered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    scheduled_at TIMESTAMP,
    performed_at TIMESTAMP,
    documented_at TIMESTAMP,
    FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    FOREIGN KEY (encounter_id) REFERENCES encounters(id) ON DELETE CASCADE,
    FOREIGN KEY (ordering_provider_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (proceduralist_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS flowsheet_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    encounter_id BIGINT,
    recorded_by_id BIGINT NOT NULL,
    blood_pressure_systolic DOUBLE PRECISION,
    blood_pressure_diastolic DOUBLE PRECISION,
    heart_rate DOUBLE PRECISION,
    respiratory_rate DOUBLE PRECISION,
    temperature DOUBLE PRECISION,
    oxygen_saturation DOUBLE PRECISION,
    mean_arterial_pressure DOUBLE PRECISION,
    fluid_intake_ml DOUBLE PRECISION,
    fluid_output_ml DOUBLE PRECISION,
    intake_source VARCHAR(255),
    output_type VARCHAR(255),
    pain_score INT,
    glasgow_coma_scale INT,
    pupil_reactivity VARCHAR(255),
    oxygen_delivery_method VARCHAR(255),
    fio2_percent DOUBLE PRECISION,
    peep_cm_h2o DOUBLE PRECISION,
    nursing_interventions VARCHAR(2000),
    sbar_handoff_note VARCHAR(3000),
    recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    FOREIGN KEY (encounter_id) REFERENCES encounters(id) ON DELETE CASCADE,
    FOREIGN KEY (recorded_by_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS triage_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    recorded_by_id BIGINT NOT NULL,
    chief_complaint VARCHAR(255),
    triage_priority VARCHAR(255) DEFAULT 'ROUTINE',
    vitals_summary VARCHAR(255),
    notes VARCHAR(1000),
    recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    FOREIGN KEY (recorded_by_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS allergies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    allergen_name VARCHAR(255) NOT NULL,
    allergen_code VARCHAR(255),
    category VARCHAR(255) NOT NULL,
    severity VARCHAR(255) NOT NULL,
    reaction_description VARCHAR(1000),
    status VARCHAR(255) DEFAULT 'ACTIVE',
    recorded_by_id BIGINT,
    recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    FOREIGN KEY (recorded_by_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS diagnoses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    doctor_id BIGINT NOT NULL,
    condition_name VARCHAR(255) NOT NULL,
    icd_code VARCHAR(255),
    snomed_code VARCHAR(255),
    onset_date DATE,
    status VARCHAR(255) DEFAULT 'ACTIVE',
    notes VARCHAR(2000),
    recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    FOREIGN KEY (doctor_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS medical_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    doctor_id BIGINT NOT NULL,
    diagnosis VARCHAR(255) NOT NULL,
    icd_code VARCHAR(255),
    symptoms VARCHAR(2000),
    treatment_plan VARCHAR(2000),
    notes VARCHAR(2000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    FOREIGN KEY (doctor_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS vitals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    recorded_by_id BIGINT NOT NULL,
    systolic_bp INT,
    diastolic_bp INT,
    heart_rate INT,
    temperature DOUBLE PRECISION,
    oxygen_saturation INT,
    respiratory_rate INT,
    weight_kg DOUBLE PRECISION,
    height_cm DOUBLE PRECISION,
    bmi DOUBLE PRECISION,
    blood_glucose INT,
    recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    FOREIGN KEY (recorded_by_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS prescriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    doctor_id BIGINT NOT NULL,
    medication_name VARCHAR(255) NOT NULL,
    rx_norm_code VARCHAR(255),
    dosage VARCHAR(255) NOT NULL,
    route VARCHAR(255),
    frequency VARCHAR(255) NOT NULL,
    duration_days INT,
    refills INT DEFAULT 0,
    instructions VARCHAR(1000),
    status VARCHAR(255) DEFAULT 'ACTIVE',
    prescribed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    FOREIGN KEY (doctor_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS emar_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    administered_by_id BIGINT NOT NULL,
    prescription_id BIGINT,
    medication_name VARCHAR(255),
    dose VARCHAR(255),
    route VARCHAR(255),
    status VARCHAR(255) DEFAULT 'ADMINISTERED',
    notes VARCHAR(1000),
    administered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    FOREIGN KEY (administered_by_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (prescription_id) REFERENCES prescriptions(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    doctor_id BIGINT NOT NULL,
    appointment_date TIMESTAMP NOT NULL,
    status VARCHAR(255) DEFAULT 'SCHEDULED',
    stage VARCHAR(255) DEFAULT 'SCHEDULED',
    reason VARCHAR(255),
    notes VARCHAR(1000),
    insurance_verified BOOLEAN DEFAULT FALSE,
    insurance_details VARCHAR(1000),
    reports_uploaded VARCHAR(2000),
    follow_up_date TIMESTAMP,
    arrived_at TIMESTAMP,
    vitals_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    FOREIGN KEY (doctor_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (vitals_id) REFERENCES vitals(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS appointment_cancellations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id BIGINT UNIQUE NOT NULL,
    cancelled_by_user_id BIGINT NOT NULL,
    cancelled_by_role VARCHAR(255) NOT NULL,
    cancellation_reason VARCHAR(255) NOT NULL,
    additional_comment VARCHAR(500),
    cancelled_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    refund_status VARCHAR(255) DEFAULT 'NOT_APPLICABLE',
    FOREIGN KEY (appointment_id) REFERENCES appointments(id) ON DELETE CASCADE,
    FOREIGN KEY (cancelled_by_user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS appointment_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    author_name VARCHAR(255) NOT NULL,
    author_role VARCHAR(255) NOT NULL,
    note_type VARCHAR(255) NOT NULL,
    content VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    is_edited BOOLEAN DEFAULT FALSE,
    edit_history_json VARCHAR(4000),
    FOREIGN KEY (appointment_id) REFERENCES appointments(id) ON DELETE CASCADE,
    FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS appointment_lab_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id BIGINT NOT NULL,
    test_name VARCHAR(255) NOT NULL,
    priority VARCHAR(255) DEFAULT 'ROUTINE',
    clinical_indications VARCHAR(1000),
    ordered_by_id BIGINT NOT NULL,
    ordered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (appointment_id) REFERENCES appointments(id) ON DELETE CASCADE,
    FOREIGN KEY (ordered_by_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS appointment_billings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id BIGINT UNIQUE NOT NULL,
    consultation_fee DOUBLE PRECISION DEFAULT 100.0,
    triage_fee DOUBLE PRECISION DEFAULT 25.0,
    lab_fee DOUBLE PRECISION DEFAULT 0.0,
    pharmacy_fee DOUBLE PRECISION DEFAULT 0.0,
    insurance_coverage DOUBLE PRECISION DEFAULT 0.0,
    net_payable DOUBLE PRECISION DEFAULT 125.0,
    payment_status VARCHAR(255) DEFAULT 'PENDING',
    generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (appointment_id) REFERENCES appointments(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS abac_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_name VARCHAR(60) UNIQUE NOT NULL,
    target_resource VARCHAR(50) NOT NULL,
    action VARCHAR(20) NOT NULL,
    spel_expression VARCHAR(255) NOT NULL,
    active BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255),
    user_role VARCHAR(255),
    action VARCHAR(255),
    entity_name VARCHAR(255),
    resource_id VARCHAR(255),
    ip_address VARCHAR(255) DEFAULT '127.0.0.1',
    details VARCHAR(2000),
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
