-- ==============================================================================
-- Sentinel EHR Database Schema Script (DDL)
-- Compatible with Database SQL Editors (H2 Oracle Mode, Oracle DB, PostgreSQL, MySQL)
-- ==============================================================================

CREATE TABLE IF NOT EXISTS departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(60) UNIQUE NOT NULL,
    code VARCHAR(20) UNIQUE NOT NULL,
    description VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30) UNIQUE NOT NULL,
    description VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(60) UNIQUE NOT NULL,
    category VARCHAR(30) NOT NULL,
    description VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS role_permissions (
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
    FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    specialization VARCHAR(255),
    department VARCHAR(255),
    department_id BIGINT,
    license_number VARCHAR(255),
    qualifications VARCHAR(255),
    years_of_experience INT,
    medical_board_state VARCHAR(255),
    verification_status VARCHAR(255) DEFAULT 'VERIFIED',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_code VARCHAR(255) UNIQUE NOT NULL,
    abha_id VARCHAR(255),
    national_id VARCHAR(255),
    full_name VARCHAR(255) NOT NULL,
    date_of_birth DATE,
    gender VARCHAR(255),
    blood_type VARCHAR(255),
    phone VARCHAR(255),
    email VARCHAR(255),
    address VARCHAR(255),
    pin_code VARCHAR(255),
    emergency_contact VARCHAR(255),
    insurance_provider VARCHAR(255),
    insurance_policy_number VARCHAR(255),
    insurance_group_number VARCHAR(255),
    coverage_plan VARCHAR(255),
    medical_alerts VARCHAR(1000),
    user_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS patient_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    staff_user_id BIGINT NOT NULL,
    assignment_type VARCHAR(40) NOT NULL,
    start_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    end_date TIMESTAMP,
    FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    FOREIGN KEY (staff_user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS encounters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    attending_provider_id BIGINT NOT NULL,
    encounter_type VARCHAR(255) NOT NULL,
    chief_complaint VARCHAR(1000),
    clinical_notes VARCHAR(3000),
    discharge_summary VARCHAR(3000),
    status VARCHAR(255) DEFAULT 'ACTIVE',
    encounter_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    FOREIGN KEY (attending_provider_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS allergies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    allergen_name VARCHAR(255) NOT NULL,
    allergen_code VARCHAR(255),
    category VARCHAR(255) NOT NULL,
    severity VARCHAR(255) NOT NULL,
    reaction_description VARCHAR(1000),
    status VARCHAR(255) DEFAULT 'ACTIVE',
    recorded_by_id BIGINT,
    recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    FOREIGN KEY (recorded_by_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS diagnoses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    doctor_id BIGINT NOT NULL,
    condition_name VARCHAR(255) NOT NULL,
    icd_code VARCHAR(255),
    snomed_code VARCHAR(255),
    onset_date DATE,
    status VARCHAR(255) DEFAULT 'ACTIVE',
    notes VARCHAR(2000),
    recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    FOREIGN KEY (doctor_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS medical_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    doctor_id BIGINT NOT NULL,
    diagnosis VARCHAR(255) NOT NULL,
    icd_code VARCHAR(255),
    symptoms VARCHAR(2000),
    treatment_plan VARCHAR(2000),
    notes VARCHAR(2000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    FOREIGN KEY (doctor_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS vitals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    recorded_by_id BIGINT NOT NULL,
    blood_pressure VARCHAR(255),
    heart_rate INT,
    temperature DOUBLE PRECISION,
    oxygen_saturation INT,
    respiratory_rate INT,
    weight_kg DOUBLE PRECISION,
    height_cm DOUBLE PRECISION,
    bmi DOUBLE PRECISION,
    blood_glucose INT,
    recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    FOREIGN KEY (recorded_by_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS prescriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    doctor_id BIGINT NOT NULL,
    medication_name VARCHAR(255) NOT NULL,
    rx_norm_code VARCHAR(255),
    dosage VARCHAR(255) NOT NULL,
    route VARCHAR(255),
    frequency VARCHAR(255) NOT NULL,
    duration_days INT,
    refills INT DEFAULT 0,
    instructions VARCHAR(1000),
    status VARCHAR(255) DEFAULT 'ACTIVE',
    prescribed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    FOREIGN KEY (doctor_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    doctor_id BIGINT NOT NULL,
    appointment_date TIMESTAMP NOT NULL,
    status VARCHAR(255) DEFAULT 'SCHEDULED',
    stage VARCHAR(255) DEFAULT 'SCHEDULED',
    reason VARCHAR(255),
    notes VARCHAR(1000),
    insurance_verified BOOLEAN DEFAULT FALSE,
    insurance_details VARCHAR(1000),
    reports_uploaded VARCHAR(2000),
    follow_up_date TIMESTAMP,
    vitals_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    FOREIGN KEY (doctor_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (vitals_id) REFERENCES vitals(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS appointment_cancellations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id BIGINT UNIQUE NOT NULL,
    cancelled_by_user_id BIGINT NOT NULL,
    cancelled_by_role VARCHAR(255) NOT NULL,
    cancellation_reason VARCHAR(255) NOT NULL,
    additional_comment VARCHAR(500),
    cancelled_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    refund_status VARCHAR(255) DEFAULT 'NOT_APPLICABLE',
    FOREIGN KEY (appointment_id) REFERENCES appointments(id) ON DELETE CASCADE,
    FOREIGN KEY (cancelled_by_user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS appointment_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    author_name VARCHAR(255) NOT NULL,
    author_role VARCHAR(255) NOT NULL,
    note_type VARCHAR(255) NOT NULL,
    content VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    is_edited BOOLEAN DEFAULT FALSE,
    edit_history_json VARCHAR(4000),
    FOREIGN KEY (appointment_id) REFERENCES appointments(id) ON DELETE CASCADE,
    FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS appointment_lab_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id BIGINT NOT NULL,
    test_name VARCHAR(255) NOT NULL,
    priority VARCHAR(255) DEFAULT 'ROUTINE',
    clinical_indications VARCHAR(1000),
    ordered_by_id BIGINT NOT NULL,
    ordered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (appointment_id) REFERENCES appointments(id) ON DELETE CASCADE,
    FOREIGN KEY (ordered_by_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS appointment_billings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id BIGINT UNIQUE NOT NULL,
    consultation_fee DOUBLE PRECISION DEFAULT 100.0,
    triage_fee DOUBLE PRECISION DEFAULT 25.0,
    lab_fee DOUBLE PRECISION DEFAULT 0.0,
    pharmacy_fee DOUBLE PRECISION DEFAULT 0.0,
    insurance_coverage DOUBLE PRECISION DEFAULT 0.0,
    net_payable DOUBLE PRECISION DEFAULT 125.0,
    payment_status VARCHAR(255) DEFAULT 'PENDING',
    generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (appointment_id) REFERENCES appointments(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS abac_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_name VARCHAR(60) UNIQUE NOT NULL,
    target_resource VARCHAR(50) NOT NULL,
    action VARCHAR(20) NOT NULL,
    spel_expression VARCHAR(255) NOT NULL,
    active BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255),
    user_role VARCHAR(255),
    action VARCHAR(255),
    entity_name VARCHAR(255),
    resource_id VARCHAR(255),
    ip_address VARCHAR(255) DEFAULT '127.0.0.1',
    details VARCHAR(2000),
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

